config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#all_products'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  devise_for :users
  resource :user, shallow: true do
    resources :products, shallow: true do
      get 'all_products', on: :collection
      resources :comments
    end
  end

  resources :carts, only: %i[show index] do
    member do
      put 'update_quantity', as: 'update_quantity'
      post 'add_to_cart', as: 'add_to'
      delete 'remove_from_cart', as: 'remove_from'
    end
  end

  resource :checkouts, only: [:create] do
    member do
      get 'success'
      get 'cancel'
    end
  end

end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  include CartsHelper
  def index
    @total_price = total(@cart)
  end

  def show
    @total_price = total(@cart)
  end

  def add_to_cart
    session[:cart][params[:id].to_i] = 1
    redirect_to request.referer
  end

  def update_quantity
    return if params[:quantity].nil?

    session[:cart][params[:id].to_i] = params[:quantity]
    redirect_to request.referer
  end

  def remove_from_cart
    return if params[:id].nil?

    session[:cart].delete(params[:id])
    redirect_to request.referer
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
  def total(cart)
    total_price ||= 0
    cart.each do |cart_item|
      total_price += (session[:cart][cart_item.id.to_s]).to_i * cart_item.price.to_i
    end
    total_price
  end
end

app/views/carts/index.html.erb
<h1 class="text-center text-dark mb-5 shadow border-bottom">Your Cart</h1>
<h4>Total Basket Items: <%= @cart.count %></h4>

<div class="row">
  <%= render @cart, locals: {renderer: @renderer} %>
</div>


<% if @cart.present? %>
  <div class = "d-flex justify-content-between">
    <h4 class="">Total Price: <%= @total_price %></h4>
    <%= link_to 'Checkout Now', checkouts_path, class: "btn btn-sm btn-outline-success text-center",remote: true, method: :post, data: { disable_with: "validating..."}  %>
  </div>
<% end %>

app/views/carts/show.html.erb
<h1 class="text-center text-dark mb-5 shadow border-bottom">Your Cart</h1>
<h4>Total Basket Items: <%= @cart.count %></h4>
<div class="row">
  <%= render @cart, locals: {renderer: @renderer} %>
</div>


<% if @cart.present? %>
  <div class = "d-flex justify-content-between">
    <h4 class="">Total Price: <%= @total_price %></h4>
    <%= link_to 'Checkout Now', checkout_path, class: "btn btn-sm btn-outline-success text-center",remote: true, method: :post, data: { disable_with: "validating..."}  %>
  </div>
<% end %>