config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#all_products'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  devise_for :users
  resource :user, shallow: true do
    resources :products, shallow: true do
      get 'all_products', on: :collection
      resources :comments
    end
  end

  resources :carts, only: %i[show index] do
    member do
      put 'update_quantity', as: 'update_quantity'
      post 'add_to_cart', as: 'add_to'
      delete 'remove_from_cart', as: 'remove_from'
    end
  end

  resource :checkouts, only: [:create] do
    member do
      get 'success'
      get 'cancel'
    end
  end

end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images

  validates :name, presence: true, length: { in: 6..20, too_long: '20 characters is the maximum allowed' }
  validates :description, presence: true, length: { minimum: 20 }
  validates :quantity, numericality: { only_integer: true, greater_than: 0, less_than: 50_000 }
  validates :price, numericality: { only_integer: true, greater_than: 0, less_than: 1_000_000 }

  scope :all_products_except_mine, ->(id) { where.not(user_id: id) }

  after_create :create_stripe_product

  private

  def create_stripe_product
    product = Stripe::Product.create(name: name)
    price = Stripe::Price.create(product: product, unit_amount: self.price, currency: 'usd')
    update(stripe_product_id: product.id, stripe_price_id: price.id)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  # include ActiveStorage::SetCurrent
  include ApplicationHelper
  before_action :authenticate_user!, except: %i[index show all_products]
  before_action :set_product, only: %i[show edit update destroy]
  # before_action :set_product, except: %i[new create index]
  before_action :authorize_product, only: %i[edit update destroy]

  after_action :verify_authorized, only: %i[edit update destroy]

  def index
    @products = current_user.products
  end

  def all_products
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)

    @products = @q.result(distinct: true).all_products_except_mine(current_user) if user_signed_in?
    render json: {status: 'SUCCESS', message: 'Loaded Products', data: @products}, status: :ok, include: [images: {methods: :service_url}]
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    if @product.destroy
      redirect_to user_products_path
    else
      flash[:alert] = 'There is some error in destroying Product'
    end
  end

  def show
    render json: {status: 'SUCCESS', message: 'Loaded Product', data: @product }, status: :ok,  include: [images: {methods: :service_url}]
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def authorize_product
    authorize @product
  end

  def product_params
    params.require(:product).permit(:name, :description, :quantity, :price, images: [])
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with model: model_type, local: true do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> Prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, min: 1 %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, min: 1 %>
  </div>

  <div class="field">
    <%= form.label :images %><br />
    <%= form.file_field :images, multiple: true, autofocus: true, accept:'image/*' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>

app/views/products/_product.html.erb
<div class=" col-3 p-3" style="">
  <div class="card" style="width: 18rem;">
    <% if product.images.attached? && controller_name != 'carts'%>
      <%= image_tag(product.images[0], size: 300, class:"card-img-top") %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= product.name %></h5>
      <p class="card-text">Rs. <%= product.price %></p>
      <div>
        <% if controller_name == 'products' && action_name == 'all_products' %>
          <%= link_to 'Show', product, class: "btn btn-sm btn-outline-dark w-100 mt-2 shadow" %>
          <%= link_to 'Add to Basket', add_to_cart_path(product.id),remote: true, class: "btn btn-sm btn-outline-dark w-100 mt-2 shadow", method: :post unless @cart.include?(product) %>
          <%= link_to 'Remove from Basket',  remove_from_cart_path(product),remote: true, class: "btn btn-sm btn-outline-dark w-100 mt-2 shadow" , method: :delete if @cart.include?(product)%>
        <% elsif controller_name == 'products' && action_name == 'index' %>
          <%= link_to 'Show', product, class: "btn btn-sm btn-outline-dark w-100 mt-2 shadow" %>
          <%= link_to 'Edit', edit_product_path(product), class: "btn btn-sm btn-outline-dark w-100 mt-2 shadow" if policy(product).update? %>
          <%= link_to 'Destroy', product_path(product), class: "btn btn-sm btn-outline-dark w-100 mt-2 shadow", method: :delete, data: { confirm: 'Are you sure?' } if policy(product).destroy? %>
        <% elsif controller_name == 'carts' %>
          <p>Quantity <%= session[:cart][product.id.to_s]%></p>
          <%= form_with url: update_quantity_cart_url(product), method: :put , remote: true do |form| %>
            <%= form.number_field :quantity , value: session[:cart][product.id.to_s], min: 1, size: 2  %>
            <%= form.submit "Update Quantity", class: "w-100 mt-2"  %>
          <% end  %>
          <%= link_to 'Show', product, class: "btn btn-sm btn-outline-dark w-100 mt-2 shadow" %>
          <%= link_to 'Remove from Basket',  remove_from_cart_path(product),remote: true, class: "btn btn-sm btn-outline-dark w-100 mt-2 shadow" , method: :delete if @cart.include?(product)%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/all_products.html.erb
<h1 class="text-center text-dark mb-5 shadow border-bottom">All Products</h1>

<div class="row">
  <%= render @products%>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product, model_type: [@product] %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', user_products_path %>

app/views/products/index.html.erb
<h1 class= "text-center text-dark mb-5 shadow border-bottom">My Products</h1>
<div class="row">
  <%= render @products %>
</div>

app/views/products/my_products.html.erb
<h1 class= "text-center text-dark mb-5 shadow border-bottom">My Products</h1>
<div class="row">
  <%= render current_user.products %>
</div>

app/views/products/new.html.erb
<h1>Add Product</h1>

<%= render 'form', product: @product, model_type: [:user, @product] %>

app/views/products/show.html.erb
<div class="container mt-5 mb-5">
  <div class="card shadow">
    <div class="row g-0">
      <div class="col-md-6 border-end">
        <div class="d-flex flex-column justify-content-center">
          <div class="main_image">
            <% if @product.images.attached? %>
              <% @product.images.each do |image| %>
                <%= image_tag(image, width:'300', height: '300') %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="p-3 right-side">
          <div class="d-flex justify-content-between align-items-center">
            <h3><%= @product.name %></h3>
          </div>
          <div class="mt-2 pr-3 content">
            <p><%= @product.description %></p>
          </div>
          <h3>Rs. <%= @product.price %></h3>
          <br>
          <div class="buttons d-flex flex-row mt-5 gap-3">
            <%# <%= link_to 'Add to Basket', add_to_cart_path(@product.id),remote: true, class: "btn btn-sm btn-outline-dark", method: :post unless @cart.include?(@product) && policy(@product). %>
            <%= link_to 'Remove from Basket',  remove_from_cart_path(@product),remote: true, class: "btn btn-sm btn-outline-dark" , method: :delete if @cart.include?(@product) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render @product.comments %>
<%= render 'comments/form', comment: @comment, model_type: [@product, @product.comments.build], url: product_comments_path(@product, @comment) if policy(@product).comment? && user_signed_in? %>

<%= link_to 'Back', root_path, class: "btn btn-sm btn-outline-dark" %>