config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#all_products'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  devise_for :users
  resource :user, shallow: true do
    resources :products, shallow: true do
      get 'all_products', on: :collection
      resources :comments
    end
  end

  resources :carts, only: %i[show index] do
    member do
      put 'update_quantity', as: 'update_quantity'
      post 'add_to_cart', as: 'add_to'
      delete 'remove_from_cart', as: 'remove_from'
    end
  end

  resource :checkouts, only: [:create] do
    member do
      get 'success'
      get 'cancel'
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-lg-start mt-4">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-dark" href="/">EcommereceTestProject.com</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">E-Commerece</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Basket', carts_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Products', user_products_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Add Product', new_user_product_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav d-flex align-items-center me-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <p class="mb-0 me-3 text-muted text-uppercase"><%= current_user.name %></p>
        </li>
        <% if current_user.image.attached? %>
          <li class="nav-item">
            <%= image_tag(current_user.image, size: 25, class:"rounded-pill" ) %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link"%>
        </li>
      <% end %>
      </ul>
      <% if controller_name == 'products' && action_name == 'all_products'%>
        <%= render 'layouts/search' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_search.html.erb
<%= search_form_for @q, url: all_products_user_products_path, method: :get, class: "d-flex" do |form| %>
  <%= form.search_field :name_cont, placeholder: 'Search', class: "form-control me-2"%>
  <%= form.submit "Search", class: "btn btn-Outline-success"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Personal Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "" >
    <%= render 'layouts/header' %>
    <% if notice %>
      <p class="notice bg-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert bg-warning"><%= alert %></p>
    <% end %>

    <% if false %>
      <% if flash[:alert] %>
        <div id="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>